<?php

namespace Pipeline\Stages\AIImageGeneration;
require_once PLUGIN_PATH . "classes/Pipeline/Utils/Helpers.php";
require_once PLUGIN_PATH . "classes/Pipeline/Stages/AIImageGeneration/AIImageGenerationStage.php";
require_once PLUGIN_PATH . "classes/Pipeline/Interfaces/AbstractStageFactory.php";
require_once PLUGIN_PATH . "classes/Pipeline/StageConfiguration/StageConfiguration.php";

use Pipeline\Interfaces\AbstractPipelineStage;
use Pipeline\Interfaces\AbstractStageFactory;
use Pipeline\StageDescriptor;
use Pipeline\Utils\Helpers;
use Pipeline\StageConfiguration\StageConfiguration;

class AIImageGenerationStageFactory implements AbstractStageFactory
{
    /**
     * @inheritDoc
     */
    public function instantiate(StageConfiguration $configuration): AbstractPipelineStage
    {
        //TODO: validate $configuration
        return new AIImageGenerationStage($configuration);
    }

    /**
     * @inheritDoc
     */
    public function getStageDescriptor(): StageDescriptor
    {
        $description = "Generates one or more images with OpenAI and outputs the generated image urls into the output context.";
        $setupParameters = array(
            "prompt" => "The image generation prompt for the AI. You can use Context Placeholders to feed context values (i.e. results from previous stages) into the prompt.",
            "resultTo" => "(optional) The name of the context parameter to which the generated images URLS are saved",
            "count" => "(optional, default: 1) An integer which specified the number of images to generate.",
            "highFidelity" => "(optional, default: false) A boolean which specifies if the images should be generated with higher quality. Implies higher costs.",
            "size" => "(optional, default: \"512x512\") A string specifying the size of the generated image, i.e. \"512x512\". The specified size must by supported by the selected model",
            "model" => "(optional, default: dall-e-2) The OpenAI model to use for image generation",
        );

        $contextInputs = array(
            "OPENAI_API_KEY" => "The OpenAI's API key to use to perform the image generation api request to OpenAI.",
        );

        $contextOutputs = array(
            "GENERATED_IMAGES_URL" => "An array of strings with the URLs of the images generated by the AI. If resultTo input settings parameter is setup, the output image urls is set into the context parameter specified there instead.",
        );

        return new StageDescriptor("AIImageGeneration", $description, $setupParameters, $contextInputs, $contextOutputs);
    }
}